[build]
  # Base directory for the build (if your package.json is in root, leave blank)
  base = "/"
  
  # Build command (same as in package.json)
  command = "npm run build"
  
  # Directory containing the built files
  publish = "dist"

[build.environment]
  # Node.js version (optional but recommended)
  NODE_VERSION = "20"

# Required for Single Page Applications (SPA) like React, Vue, etc.
# This ensures all routes are handled by index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Header settings for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # CORS headers (if needed for API calls)
    Access-Control-Allow-Origin = "https://your-backend.onrender.com"

# Optional: Environment variables (alternative to UI setting)
[context.production.environment]
  VITE_API_URL = "https://your-backend-service.onrender.com"

[context.deploy-preview.environment]
  VITE_API_URL = "https://your-backend-service.onrender.com"

[context.branch-deploy.environment]
  VITE_API_URL = "https://your-backend-service.onrender.com"